// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template
{
    
    
    public class BuildingSettingTemplateVODataReader : ITemplateReader
    {
        
        public System.Collections.Generic.List<object> GenerateByteArray(byte[] bytes)
        {
            ByteArray data = new ByteArray(bytes);
            System.Collections.Generic.List<object> list = new System.Collections.Generic.List<object>();
            int length = data.ReadInt();
            for (int i = 0; (i < length); i = (i + 1))
            {
                BuildingSettingTemplateVO vo = new BuildingSettingTemplateVO();
                vo.id = data.ReadInt();
                vo.fuxingSquirePopu = data.ReadInt();
                vo.beastiaryPopu = data.ReadInt();
                vo.herohouseNumber = data.ReadInt();
                vo.mineNeedminer = data.ReadInt();
                vo.minerMax = data.ReadInt();
                vo.currencyMax = data.ReadInt();
                vo.currencyProtectRate = data.ReadInt();
                vo.currencyProtectVal = data.ReadInt();
                vo.def = data.ReadInt();
                vo.myOrderNumber = data.ReadInt();
                list.Add(vo);
            }
            return list;
        }
    }
}
