// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template
{
    
    
    public class ChargeTemplateVODataReader : ITemplateReader
    {
        
        public System.Collections.Generic.List<object> GenerateByteArray(byte[] bytes)
        {
            ByteArray data = new ByteArray(bytes);
            System.Collections.Generic.List<object> list = new System.Collections.Generic.List<object>();
            int length = data.ReadInt();
            for (int i = 0; (i < length); i = (i + 1))
            {
                ChargeTemplateVO vo = new ChargeTemplateVO();
                vo.id = data.ReadInt();
                vo.type = data.ReadInt();
                vo.goodsId = data.ReadUTF();
                vo.goodsName = data.ReadUTF();
                vo.diamondAmount = data.ReadInt();
                vo.price = data.ReadFloat();
                vo.discount = data.ReadInt();
                vo.realPrice = data.ReadFloat();
                vo.currency = data.ReadUTF();
                vo.desc = data.ReadUTF();
                vo.icon_id = data.ReadUTF();
                list.Add(vo);
            }
            return list;
        }
    }
}
