// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template
{
    
    
    public class EquipTemplateVODataReader : ITemplateReader
    {
        
        public System.Collections.Generic.List<object> GenerateByteArray(byte[] bytes)
        {
            ByteArray data = new ByteArray(bytes);
            System.Collections.Generic.List<object> list = new System.Collections.Generic.List<object>();
            int length = data.ReadInt();
            for (int i = 0; (i < length); i = (i + 1))
            {
                EquipTemplateVO vo = new EquipTemplateVO();
                vo.id = data.ReadInt();
                vo.name = data.ReadUTF();
                vo.quality = data.ReadInt();
                vo.pos = data.ReadInt();
                vo.seq = data.ReadInt();
                vo.property1 = data.ReadUTF();
                vo.valueRange1 = data.ReadUTF();
                vo.property2 = data.ReadUTF();
                vo.valueRange2 = data.ReadUTF();
                vo.desc = data.ReadUTF();
                vo.talent = data.ReadUTF();
                list.Add(vo);
            }
            return list;
        }
    }
}
