// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template
{
    
    
    public class EquipSuitTemplateVODataReader : ITemplateReader
    {
        
        public System.Collections.Generic.List<object> GenerateByteArray(byte[] bytes)
        {
            ByteArray data = new ByteArray(bytes);
            System.Collections.Generic.List<object> list = new System.Collections.Generic.List<object>();
            int length = data.ReadInt();
            for (int i = 0; (i < length); i = (i + 1))
            {
                EquipSuitTemplateVO vo = new EquipSuitTemplateVO();
                vo.id = data.ReadInt();
                vo.talentId = data.ReadInt();
                vo.equip1 = data.ReadInt();
                vo.equip2 = data.ReadInt();
                vo.equip3 = data.ReadInt();
                vo.equip4 = data.ReadInt();
                vo.equip5 = data.ReadInt();
                vo.equip6 = data.ReadInt();
                vo.equip7 = data.ReadInt();
                vo.equip8 = data.ReadInt();
                list.Add(vo);
            }
            return list;
        }
    }
}
