// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template
{
    
    
    public class GuideTemplateVODataReader : ITemplateReader
    {
        
        public System.Collections.Generic.List<object> GenerateByteArray(byte[] bytes)
        {
            ByteArray data = new ByteArray(bytes);
            System.Collections.Generic.List<object> list = new System.Collections.Generic.List<object>();
            int length = data.ReadInt();
            for (int i = 0; (i < length); i = (i + 1))
            {
                GuideTemplateVO vo = new GuideTemplateVO();
                vo.id = data.ReadInt();
                vo.isComplete = data.ReadInt();
                vo.isForce = data.ReadInt();
                vo.backIndex = data.ReadInt();
                vo.guidePath = data.ReadUTF();
                vo.paramType = data.ReadInt();
                vo.param1 = data.ReadUTF();
                vo.param2 = data.ReadUTF();
                vo.param3 = data.ReadUTF();
                vo.param4 = data.ReadUTF();
                list.Add(vo);
            }
            return list;
        }
    }
}
