// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template
{
    
    
    public class MapMonsterTemplateVODataReader : ITemplateReader
    {
        
        public System.Collections.Generic.List<object> GenerateByteArray(byte[] bytes)
        {
            ByteArray data = new ByteArray(bytes);
            System.Collections.Generic.List<object> list = new System.Collections.Generic.List<object>();
            int length = data.ReadInt();
            for (int i = 0; (i < length); i = (i + 1))
            {
                MapMonsterTemplateVO vo = new MapMonsterTemplateVO();
                vo.id = data.ReadInt();
                vo.mapId = data.ReadInt();
                vo.type = data.ReadInt();
                vo.series = data.ReadInt();
                vo.rate = data.ReadInt();
                vo.name = data.ReadUTF();
                vo.baseSurrenderRate = data.ReadInt();
                vo.camp = data.ReadInt();
                vo.heroId = data.ReadInt();
                vo.level = data.ReadInt();
                vo.suitId = data.ReadInt();
                vo.attack = data.ReadInt();
                vo.def = data.ReadInt();
                vo.speed = data.ReadInt();
                vo.leadership = data.ReadInt();
                vo.actorId1 = data.ReadInt();
                vo.actorNum1 = data.ReadInt();
                vo.actorId2 = data.ReadInt();
                vo.actorNum2 = data.ReadInt();
                vo.actorId3 = data.ReadInt();
                vo.actorNum3 = data.ReadInt();
                vo.actorId4 = data.ReadInt();
                vo.actorNum4 = data.ReadInt();
                vo.actorId5 = data.ReadInt();
                vo.actorNum5 = data.ReadInt();
                list.Add(vo);
            }
            return list;
        }
    }
}
