// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template
{
    
    
    public class MapSettingTemplateVODataReader : ITemplateReader
    {
        
        public System.Collections.Generic.List<object> GenerateByteArray(byte[] bytes)
        {
            ByteArray data = new ByteArray(bytes);
            System.Collections.Generic.List<object> list = new System.Collections.Generic.List<object>();
            int length = data.ReadInt();
            for (int i = 0; (i < length); i = (i + 1))
            {
                MapSettingTemplateVO vo = new MapSettingTemplateVO();
                vo.id = data.ReadInt();
                vo.name = data.ReadUTF();
                vo.normalRate = data.ReadInt();
                vo.blackMarketRate = data.ReadInt();
                vo.campRate = data.ReadInt();
                vo.mineRate = data.ReadInt();
                vo.heroRate = data.ReadInt();
                vo.dragonRate = data.ReadInt();
                vo.robRate = data.ReadInt();
                vo.playerRate = data.ReadInt();
                vo.surrender = data.ReadInt();
                vo.needExploreDegree = data.ReadInt();
                list.Add(vo);
            }
            return list;
        }
    }
}
