// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template
{
    
    
    public class MapTemplateVODataReader : ITemplateReader
    {
        
        public System.Collections.Generic.List<object> GenerateByteArray(byte[] bytes)
        {
            ByteArray data = new ByteArray(bytes);
            System.Collections.Generic.List<object> list = new System.Collections.Generic.List<object>();
            int length = data.ReadInt();
            for (int i = 0; (i < length); i = (i + 1))
            {
                MapTemplateVO vo = new MapTemplateVO();
                vo.id = data.ReadInt();
                vo.name = data.ReadUTF();
                vo.isOpen = data.ReadInt();
                vo.camp = data.ReadInt();
                vo.heroConfig = data.ReadUTF();
                vo.monsterConfig = data.ReadUTF();
                vo.specialty = data.ReadInt();
                vo.needHeroLevel = data.ReadInt();
                vo.everyHourExp = data.ReadInt();
                vo.everyHourGold = data.ReadInt();
                vo.everyHourWood = data.ReadInt();
                vo.everyHourCrystal = data.ReadInt();
                vo.everyHourStone = data.ReadInt();
                vo.everyHourSulfur = data.ReadInt();
                vo.everyHourDiamond = data.ReadInt();
                list.Add(vo);
            }
            return list;
        }
    }
}
