// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template
{
    
    
    public class TalentTemplateVODataReader : ITemplateReader
    {
        
        public System.Collections.Generic.List<object> GenerateByteArray(byte[] bytes)
        {
            ByteArray data = new ByteArray(bytes);
            System.Collections.Generic.List<object> list = new System.Collections.Generic.List<object>();
            int length = data.ReadInt();
            for (int i = 0; (i < length); i = (i + 1))
            {
                TalentTemplateVO vo = new TalentTemplateVO();
                vo.id = data.ReadInt();
                vo.type = data.ReadInt();
                vo.name = data.ReadUTF();
                vo.calcPos = data.ReadUTF();
                vo.descTxt = data.ReadUTF();
                vo.param1 = data.ReadUTF();
                vo.param2 = data.ReadUTF();
                vo.param3 = data.ReadUTF();
                vo.magicalResist = data.ReadInt();
                vo.atkAnimation = data.ReadInt();
                vo.atkEffect = data.ReadUTF();
                vo.defEffect = data.ReadUTF();
                list.Add(vo);
            }
            return list;
        }
    }
}
