// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Template.Editor
{
    using System.Collections.Generic;
    
    
    public class BuildingSettingTemplateVODataWriter : ITemplaterWriter
    {
        
        public ByteArray GenerateByteArray(object data)
        {
            List<BuildingSettingTemplateVO> list = data as List<BuildingSettingTemplateVO>;
            ByteArray ba = new ByteArray();
            int length = list.Count;
            ba.WriteInt(length);
            for (int i = 0; (i < length); i = (i + 1))
            {
                ba.WriteInt(list[i].id);
                ba.WriteInt(list[i].fuxingSquirePopu);
                ba.WriteInt(list[i].beastiaryPopu);
                ba.WriteInt(list[i].herohouseNumber);
                ba.WriteInt(list[i].mineNeedminer);
                ba.WriteInt(list[i].minerMax);
                ba.WriteInt(list[i].currencyMax);
                ba.WriteInt(list[i].currencyProtectRate);
                ba.WriteInt(list[i].currencyProtectVal);
                ba.WriteInt(list[i].def);
                ba.WriteInt(list[i].myOrderNumber);
            }
            return ba;
        }
    }
}
