/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Limbo.Net
{
  public enum VariableType
  {
    BOOL = 1,
    BYTE = 2,
    INT = 3,
    DOUBLE = 4,
    STR = 5,
    BYTEARR = 6,
    MAP = 7,
    LIST = 8,
    SET = 9,
  }
}
